config/routes.rb
YardsaleApp::Application.routes.draw do

  devise_for :users

  resources :locations do
    resources :items
  end

end

app/models/item.rb
class Item < ActiveRecord::Base

  belongs_to :location
  belongs_to :user

  validates_presence_of :name
  validates_presence_of :description
  validates_presence_of :price

  validates_presence_of :user_id

  validates_presence_of :latitude
  validates_presence_of :longitude

  validates_presence_of :location_id

end

app/models/location.rb
class Location < ActiveRecord::Base

has_many :items
has_many :users, through: :items

validates_presence_of :city
validates_presence_of :state
validates_presence_of :zip_code


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :items

  has_many :locations, through: :items


  validates_presence_of :first_name
  validates_presence_of :last_name

  validates_presence_of :email

  validates_uniqueness_of :email

  VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email,
      :password, :password_confirmation) }
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!

  def index
    @items = Item.all
  end

  def new
    @location = Location.find(params[:location_id])
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @location = Location.find(params[:location_id])
    @item = @location.items.build(item_params)
    @item.user_id = current_user.id
    if @item.save
      flash[:notice] = "Item Added"
      redirect_to @location
    else
      flash[:alert] = "Item Not Added"
      render 'new'
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :price, :latitude, :longitude, user_id: current_user)
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @locations = Location.all
  end

  def new
    @location = Location.new
  end

  def show
    @location = Location.find(params[:id])
    @item = Item.new
    @items = Item.where(location_id: 1)
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      flash[:notice] = "Location Added"
      redirect_to @location
    else
      flash[:alert] = "Location Not Added"
      render 'new'
    end
  end

  private

  def location_params
    params.require(:location).permit(:city, :state, :zip_code)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/new.html.erb
<div class="row">
  <div class="large-6 large-centered columns">
    <h1>New Item Form</h1>

    <div>
      <%= simple_form_for [@location, @item] do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :price %>
        <%= f.hidden_field :latitude, readonly: true %>
        <%= f.hidden_field :latitude, readonly: true %>

        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="row">

  <div class="large-6 large-centered columns">
    <h1><%= @item.name %></h1>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>

    <!-- This is where the public api key for the google map-->

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCYEHk649Z4tAbBYyT_vn7X6UUuayebxs0&sensor=true"></script>
  </head>

  <body>

    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: "#{name} alert-box" %>
    <% end %>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/locations/index.html.erb
<div class="row">
  <div class="large-6 large-centered columns">
  <h1>Location Index</h1>

  <% @locations.each do |location| %>

    <%= link_to location.city, location_path(location) %>

  <% end %>
  </div>
</div>

app/views/locations/new.html.erb
<div class="row">
  <div class="large-6 large-centered columns">
    <h1>New City</h1>

    <%= simple_form_for @location do |f| %>
      <%= f.input :city %>
      <%= f.input :state %>
      <%= f.input :zip_code %>

      <%= f.submit %>

    <% end %>
  </div>
</div>

app/views/locations/show.html.erb
<div class="row">
  <div class="large-3 columns"></div>
  <div class="large-6 large-centered columns">
   <h1 class="text-center"><%= @location.city %></h1>
    <div id="map-canvas" class="map">
    </div>
  </div>
  <div class="large-3 columns"></div>
</div>

<%= render 'shared/new_item' %>

app/views/shared/_new_item.html.erb
<div class="row">
  <div class="large-6 large-centered columns">

    <div>
      <%= simple_form_for [@location, @item] do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :price %>
        <%= f.hidden_field :latitude, readonly: true %>
        <%= f.hidden_field :longitude, readonly: true %>

        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>